# Generated by Django 5.1.5 on 2025-02-05 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ComponentsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BikeConfigurationPerBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComponentsApp.bikemodelcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='BikeModelBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('typeId', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('typeColor', models.CharField(blank=True, max_length=50, null=True)),
                ('components', models.ManyToManyField(through='BikesApp.BikeConfigurationPerBike', to='ComponentsApp.bikemodelcomponent')),
            ],
        ),
        migrations.AddField(
            model_name='bikeconfigurationperbike',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikesApp.bikemodelbike'),
        ),
    ]
